# Generated by Django 5.2.6 on 2026-01-20 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_customuser_independent_articles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="journalist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journalist_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
