# Generated by Django 5.2.6 on 2026-01-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_rename_journalist_article_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="author",
            new_name="journalist",
        ),
    ]
