# Generated by Django 5.2.6 on 2026-01-19 15:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newsletter",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="journalist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="news.publisher",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="independent_articles",
            field=models.ManyToManyField(
                blank=True, related_name="independent_journalists", to="news.article"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="independent_newsletters",
            field=models.ManyToManyField(
                blank=True, related_name="independent_journalists", to="news.newsletter"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("journalist", "Journalist"),
                    ("editor", "Editor"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletters",
                to="news.publisher",
            ),
        ),
    ]
