# Generated by Django 5.2.6 on 2026-01-20 03:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_article_created_at_newsletter_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="independent_articles",
            field=models.ManyToManyField(
                blank=True, related_name="owning_journalists", to="news.article"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="independent_newsletters",
            field=models.ManyToManyField(
                blank=True, related_name="owning_journalists", to="news.newsletter"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="subscribed_journalists",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribed_readers_journalist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
