# Generated by Django 5.2.6 on 2026-01-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_article_journalist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="journalist",
            new_name="author",
        ),
    ]
