# Generated by Django 5.2.6 on 2026-01-20 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_rename_author_article_journalist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="subscribed_journalists",
            field=models.ManyToManyField(
                blank=True, related_name="subscribers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
